name: Bug Report
description: File a bug report
labels: [bug]
body:
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: nbpreview-version
    attributes:
      label: nbpreview version
      description: |
        What version of nbpreview are you using?

        Tip: Run `nbpreview --version`
      placeholder: "0.5.0"
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Output
      description: Display the output of the program.
      placeholder: Share a rendered notebook, traceback, screenshot, or file of captured output.
    validations:
      required: false
  - type: textarea
    id: notebook
    attributes:
      label: Notebook
      description: |
        Upload the notebook that caused the issue. Reduce the notebook to the minimal number of cells and content that can be used to reproduce the issue.
      placeholder: You can attach files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: input
    id: os
    attributes:
      label: OS
      description: What OS are you running on when you experience the issue?
      placeholder: "macOS"
    validations:
      required: false
  - type: input
    id: terminal
    attributes:
      label: Terminal
      description: What terminal are you using when you experience the issue?
      placeholder: "iTerm2"
    validations:
      required: false
  - type: input
    id: python-version
    attributes:
      label: Python version
      description: What version of python is nbpreview running on?
      placeholder: "3.9.2"
    validations:
      required: false
